language: php

php:
  - '7.2'
 
install:
- travis_retry composer install --no-interaction --prefer-source

dist: trusty

script:
  - vendor/bin/phpunit --filter testOverClearance --coverage-text --coverage-clover=coverage.clover